//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется MFCApplicationClient.rc
//
#define IDD_MFCAPPLICATIONCLIENT_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDC_BUTTON_LOAD_IMAGE           1000
#define IDC_INPUT_IMAGE                 1001
#define IDC_OUTPUT_IMAGE                1002
#define IDC_BUTTON_MEDIAN_FILTERING_GPU 1004
#define IDC_BUTTON_GAUSSIAN_BLUR_FILTER_CPU 1005
#define IDC_EDIT_MEDIAN_FILTER_SIZE     1006
#define IDC_PLATFORMS_LIST              1030
#define IDC_DEVICES_LIST                1031
#define IDC_STATIC_OPENCL_STATUS        1033
#define IDC_STATIC_PROCESSING_DURATION  1034
#define IDC_EDIT_MEAN_GAUSSIAN_NOISE    1036
#define IDC_EDIT_STDDEV_GAUSSIAN_NOISE  1037
#define IDC_BUTTON_GAUSSIAN_BLUR_FILTER_GPU 1038
#define IDC_EDIT_GAUSSIAN_BLUR_FILTER_SIZE 1039
#define IDC_BUTTON_MEDIAN_FILTERING_CPU 1040
#define IDC_CHECK_STATISTIC_MODE        1041
#define IDC_EDIT_SIZE_STATISTIC_COUNT_CALCULATIONS 1043
#define IDC_PROGRESS_STATISTIC          1044
#define IDC_COMBO_NOISE_TYPE            1045
#define IDC_BUTTON_APPLY_NOISE          1046
#define IDC_BUTTON_CALCULATING_STATISTIC 1047
#define IDC_COMBO_STATISTIC_FILTRATION_TYPE 1048
#define IDC_STATIC_STATISTIC_FILTRATION_TYPE 1049
#define IDC_COMBO1                      1050
#define IDC_COMBO_EDGE_FILTER_TYPE      1050
#define IDC_BUTTON_APPLY_EDGE_FILTER_GPU 1051
#define IDC_BUTTON_APPLY_EDGE_FILTER_GPU2 1052
#define IDC_BUTTON_APPLY_EDGE_FILTER_CPU 1052

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1052
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
